# Automatically generated by configure - do not modify

all:
SRC_PATH=/home/liqdbase/FEMU
TARGET_DIRS=x86_64-softmmu
GDB=
RUNC=docker
SUBDIRS=
PYTHON=/home/liqdbase/FEMU/build-femu/pyvenv/bin/python3 -B
MKVENV_ENSUREGROUP=/home/liqdbase/FEMU/build-femu/pyvenv/bin/python3 -B /home/liqdbase/FEMU/python/scripts/mkvenv.py ensuregroup  --online
GENISOIMAGE=
MESON=/home/liqdbase/FEMU/build-femu/pyvenv/bin/meson
NINJA=/usr/bin/ninja
EXESUF=
TCG_TESTS_TARGETS= x86_64-softmmu
