/* This file is autogenerated by tracetool, do not edit. */

#ifndef TRACE_ACCEL_HVF_GENERATED_TRACERS_H
#define TRACE_ACCEL_HVF_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_HVF_VM_MAP_EVENT;
extern TraceEvent _TRACE_HVF_VM_UNMAP_EVENT;
extern uint16_t _TRACE_HVF_VM_MAP_DSTATE;
extern uint16_t _TRACE_HVF_VM_UNMAP_DSTATE;
#define TRACE_HVF_VM_MAP_ENABLED 1
#define TRACE_HVF_VM_UNMAP_ENABLED 1
#include "qemu/log-for-trace.h"


#define TRACE_HVF_VM_MAP_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_HVF_VM_MAP) || \
    false)

static inline void _nocheck__trace_hvf_vm_map(uint64_t paddr, uint64_t size, void * vaddr, uint8_t flags, const char r, const char w, const char e)
{
    if (trace_event_get_state(TRACE_HVF_VM_MAP) && qemu_loglevel_mask(LOG_TRACE)) {
#line 6 "../accel/hvf/trace-events"
        qemu_log("hvf_vm_map " "paddr:0x%016"PRIx64" size:0x%08"PRIx64" vaddr:%p flags:0x%02x/%c%c%c" "\n", paddr, size, vaddr, flags, r, w, e);
#line 27 "trace/trace-accel_hvf.h"
    }
}

static inline void trace_hvf_vm_map(uint64_t paddr, uint64_t size, void * vaddr, uint8_t flags, const char r, const char w, const char e)
{
    if (true) {
        _nocheck__trace_hvf_vm_map(paddr, size, vaddr, flags, r, w, e);
    }
}

#define TRACE_HVF_VM_UNMAP_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_HVF_VM_UNMAP) || \
    false)

static inline void _nocheck__trace_hvf_vm_unmap(uint64_t paddr, uint64_t size)
{
    if (trace_event_get_state(TRACE_HVF_VM_UNMAP) && qemu_loglevel_mask(LOG_TRACE)) {
#line 7 "../accel/hvf/trace-events"
        qemu_log("hvf_vm_unmap " "paddr:0x%016"PRIx64" size:0x%08"PRIx64 "\n", paddr, size);
#line 47 "trace/trace-accel_hvf.h"
    }
}

static inline void trace_hvf_vm_unmap(uint64_t paddr, uint64_t size)
{
    if (true) {
        _nocheck__trace_hvf_vm_unmap(paddr, size);
    }
}
#endif /* TRACE_ACCEL_HVF_GENERATED_TRACERS_H */
