/* This file is autogenerated by tracetool, do not edit. */

#ifndef TRACE_QAPI_COMMANDS_MIGRATION_TRACE_EVENTS_GENERATED_TRACERS_H
#define TRACE_QAPI_COMMANDS_MIGRATION_TRACE_EVENTS_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_QMP_ENTER_QUERY_MIGRATE_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_QUERY_MIGRATE_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_MIGRATE_SET_CAPABILITIES_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_MIGRATE_SET_CAPABILITIES_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_QUERY_MIGRATE_CAPABILITIES_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_QUERY_MIGRATE_CAPABILITIES_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_MIGRATE_SET_PARAMETERS_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_MIGRATE_SET_PARAMETERS_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_QUERY_MIGRATE_PARAMETERS_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_QUERY_MIGRATE_PARAMETERS_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_MIGRATE_START_POSTCOPY_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_MIGRATE_START_POSTCOPY_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_X_COLO_LOST_HEARTBEAT_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_X_COLO_LOST_HEARTBEAT_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_MIGRATE_CANCEL_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_MIGRATE_CANCEL_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_MIGRATE_CONTINUE_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_MIGRATE_CONTINUE_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_MIGRATE_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_MIGRATE_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_MIGRATE_INCOMING_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_MIGRATE_INCOMING_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_XEN_SAVE_DEVICES_STATE_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_XEN_SAVE_DEVICES_STATE_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_XEN_SET_GLOBAL_DIRTY_LOG_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_XEN_SET_GLOBAL_DIRTY_LOG_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_XEN_LOAD_DEVICES_STATE_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_XEN_LOAD_DEVICES_STATE_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_XEN_SET_REPLICATION_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_XEN_SET_REPLICATION_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_QUERY_XEN_REPLICATION_STATUS_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_QUERY_XEN_REPLICATION_STATUS_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_XEN_COLO_DO_CHECKPOINT_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_XEN_COLO_DO_CHECKPOINT_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_QUERY_COLO_STATUS_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_QUERY_COLO_STATUS_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_MIGRATE_RECOVER_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_MIGRATE_RECOVER_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_MIGRATE_PAUSE_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_MIGRATE_PAUSE_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_CALC_DIRTY_RATE_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_CALC_DIRTY_RATE_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_QUERY_DIRTY_RATE_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_QUERY_DIRTY_RATE_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_SET_VCPU_DIRTY_LIMIT_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_SET_VCPU_DIRTY_LIMIT_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_CANCEL_VCPU_DIRTY_LIMIT_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_CANCEL_VCPU_DIRTY_LIMIT_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_QUERY_VCPU_DIRTY_LIMIT_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_QUERY_VCPU_DIRTY_LIMIT_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_QUERY_MIGRATIONTHREADS_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_QUERY_MIGRATIONTHREADS_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_SNAPSHOT_SAVE_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_SNAPSHOT_SAVE_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_SNAPSHOT_LOAD_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_SNAPSHOT_LOAD_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_SNAPSHOT_DELETE_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_SNAPSHOT_DELETE_EVENT;
extern uint16_t _TRACE_QMP_ENTER_QUERY_MIGRATE_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_QUERY_MIGRATE_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_MIGRATE_SET_CAPABILITIES_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_MIGRATE_SET_CAPABILITIES_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_QUERY_MIGRATE_CAPABILITIES_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_QUERY_MIGRATE_CAPABILITIES_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_MIGRATE_SET_PARAMETERS_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_MIGRATE_SET_PARAMETERS_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_QUERY_MIGRATE_PARAMETERS_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_QUERY_MIGRATE_PARAMETERS_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_MIGRATE_START_POSTCOPY_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_MIGRATE_START_POSTCOPY_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_X_COLO_LOST_HEARTBEAT_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_X_COLO_LOST_HEARTBEAT_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_MIGRATE_CANCEL_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_MIGRATE_CANCEL_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_MIGRATE_CONTINUE_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_MIGRATE_CONTINUE_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_MIGRATE_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_MIGRATE_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_MIGRATE_INCOMING_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_MIGRATE_INCOMING_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_XEN_SAVE_DEVICES_STATE_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_XEN_SAVE_DEVICES_STATE_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_XEN_SET_GLOBAL_DIRTY_LOG_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_XEN_SET_GLOBAL_DIRTY_LOG_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_XEN_LOAD_DEVICES_STATE_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_XEN_LOAD_DEVICES_STATE_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_XEN_SET_REPLICATION_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_XEN_SET_REPLICATION_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_QUERY_XEN_REPLICATION_STATUS_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_QUERY_XEN_REPLICATION_STATUS_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_XEN_COLO_DO_CHECKPOINT_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_XEN_COLO_DO_CHECKPOINT_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_QUERY_COLO_STATUS_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_QUERY_COLO_STATUS_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_MIGRATE_RECOVER_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_MIGRATE_RECOVER_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_MIGRATE_PAUSE_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_MIGRATE_PAUSE_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_CALC_DIRTY_RATE_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_CALC_DIRTY_RATE_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_QUERY_DIRTY_RATE_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_QUERY_DIRTY_RATE_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_SET_VCPU_DIRTY_LIMIT_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_SET_VCPU_DIRTY_LIMIT_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_CANCEL_VCPU_DIRTY_LIMIT_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_CANCEL_VCPU_DIRTY_LIMIT_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_QUERY_VCPU_DIRTY_LIMIT_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_QUERY_VCPU_DIRTY_LIMIT_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_QUERY_MIGRATIONTHREADS_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_QUERY_MIGRATIONTHREADS_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_SNAPSHOT_SAVE_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_SNAPSHOT_SAVE_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_SNAPSHOT_LOAD_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_SNAPSHOT_LOAD_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_SNAPSHOT_DELETE_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_SNAPSHOT_DELETE_DSTATE;
#define TRACE_QMP_ENTER_QUERY_MIGRATE_ENABLED 1
#define TRACE_QMP_EXIT_QUERY_MIGRATE_ENABLED 1
#define TRACE_QMP_ENTER_MIGRATE_SET_CAPABILITIES_ENABLED 1
#define TRACE_QMP_EXIT_MIGRATE_SET_CAPABILITIES_ENABLED 1
#define TRACE_QMP_ENTER_QUERY_MIGRATE_CAPABILITIES_ENABLED 1
#define TRACE_QMP_EXIT_QUERY_MIGRATE_CAPABILITIES_ENABLED 1
#define TRACE_QMP_ENTER_MIGRATE_SET_PARAMETERS_ENABLED 1
#define TRACE_QMP_EXIT_MIGRATE_SET_PARAMETERS_ENABLED 1
#define TRACE_QMP_ENTER_QUERY_MIGRATE_PARAMETERS_ENABLED 1
#define TRACE_QMP_EXIT_QUERY_MIGRATE_PARAMETERS_ENABLED 1
#define TRACE_QMP_ENTER_MIGRATE_START_POSTCOPY_ENABLED 1
#define TRACE_QMP_EXIT_MIGRATE_START_POSTCOPY_ENABLED 1
#define TRACE_QMP_ENTER_X_COLO_LOST_HEARTBEAT_ENABLED 1
#define TRACE_QMP_EXIT_X_COLO_LOST_HEARTBEAT_ENABLED 1
#define TRACE_QMP_ENTER_MIGRATE_CANCEL_ENABLED 1
#define TRACE_QMP_EXIT_MIGRATE_CANCEL_ENABLED 1
#define TRACE_QMP_ENTER_MIGRATE_CONTINUE_ENABLED 1
#define TRACE_QMP_EXIT_MIGRATE_CONTINUE_ENABLED 1
#define TRACE_QMP_ENTER_MIGRATE_ENABLED 1
#define TRACE_QMP_EXIT_MIGRATE_ENABLED 1
#define TRACE_QMP_ENTER_MIGRATE_INCOMING_ENABLED 1
#define TRACE_QMP_EXIT_MIGRATE_INCOMING_ENABLED 1
#define TRACE_QMP_ENTER_XEN_SAVE_DEVICES_STATE_ENABLED 1
#define TRACE_QMP_EXIT_XEN_SAVE_DEVICES_STATE_ENABLED 1
#define TRACE_QMP_ENTER_XEN_SET_GLOBAL_DIRTY_LOG_ENABLED 1
#define TRACE_QMP_EXIT_XEN_SET_GLOBAL_DIRTY_LOG_ENABLED 1
#define TRACE_QMP_ENTER_XEN_LOAD_DEVICES_STATE_ENABLED 1
#define TRACE_QMP_EXIT_XEN_LOAD_DEVICES_STATE_ENABLED 1
#define TRACE_QMP_ENTER_XEN_SET_REPLICATION_ENABLED 1
#define TRACE_QMP_EXIT_XEN_SET_REPLICATION_ENABLED 1
#define TRACE_QMP_ENTER_QUERY_XEN_REPLICATION_STATUS_ENABLED 1
#define TRACE_QMP_EXIT_QUERY_XEN_REPLICATION_STATUS_ENABLED 1
#define TRACE_QMP_ENTER_XEN_COLO_DO_CHECKPOINT_ENABLED 1
#define TRACE_QMP_EXIT_XEN_COLO_DO_CHECKPOINT_ENABLED 1
#define TRACE_QMP_ENTER_QUERY_COLO_STATUS_ENABLED 1
#define TRACE_QMP_EXIT_QUERY_COLO_STATUS_ENABLED 1
#define TRACE_QMP_ENTER_MIGRATE_RECOVER_ENABLED 1
#define TRACE_QMP_EXIT_MIGRATE_RECOVER_ENABLED 1
#define TRACE_QMP_ENTER_MIGRATE_PAUSE_ENABLED 1
#define TRACE_QMP_EXIT_MIGRATE_PAUSE_ENABLED 1
#define TRACE_QMP_ENTER_CALC_DIRTY_RATE_ENABLED 1
#define TRACE_QMP_EXIT_CALC_DIRTY_RATE_ENABLED 1
#define TRACE_QMP_ENTER_QUERY_DIRTY_RATE_ENABLED 1
#define TRACE_QMP_EXIT_QUERY_DIRTY_RATE_ENABLED 1
#define TRACE_QMP_ENTER_SET_VCPU_DIRTY_LIMIT_ENABLED 1
#define TRACE_QMP_EXIT_SET_VCPU_DIRTY_LIMIT_ENABLED 1
#define TRACE_QMP_ENTER_CANCEL_VCPU_DIRTY_LIMIT_ENABLED 1
#define TRACE_QMP_EXIT_CANCEL_VCPU_DIRTY_LIMIT_ENABLED 1
#define TRACE_QMP_ENTER_QUERY_VCPU_DIRTY_LIMIT_ENABLED 1
#define TRACE_QMP_EXIT_QUERY_VCPU_DIRTY_LIMIT_ENABLED 1
#define TRACE_QMP_ENTER_QUERY_MIGRATIONTHREADS_ENABLED 1
#define TRACE_QMP_EXIT_QUERY_MIGRATIONTHREADS_ENABLED 1
#define TRACE_QMP_ENTER_SNAPSHOT_SAVE_ENABLED 1
#define TRACE_QMP_EXIT_SNAPSHOT_SAVE_ENABLED 1
#define TRACE_QMP_ENTER_SNAPSHOT_LOAD_ENABLED 1
#define TRACE_QMP_EXIT_SNAPSHOT_LOAD_ENABLED 1
#define TRACE_QMP_ENTER_SNAPSHOT_DELETE_ENABLED 1
#define TRACE_QMP_EXIT_SNAPSHOT_DELETE_ENABLED 1
#include "qemu/log-for-trace.h"


#define TRACE_QMP_ENTER_QUERY_MIGRATE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_QUERY_MIGRATE) || \
    false)

static inline void _nocheck__trace_qmp_enter_query_migrate(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_QUERY_MIGRATE) && qemu_loglevel_mask(LOG_TRACE)) {
#line 3 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_enter_query_migrate " "%s" "\n", json);
#line 195 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_enter_query_migrate(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_query_migrate(json);
    }
}

#define TRACE_QMP_EXIT_QUERY_MIGRATE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_QUERY_MIGRATE) || \
    false)

static inline void _nocheck__trace_qmp_exit_query_migrate(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_QUERY_MIGRATE) && qemu_loglevel_mask(LOG_TRACE)) {
#line 4 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_exit_query_migrate " "%s %d" "\n", result, succeeded);
#line 215 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_exit_query_migrate(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_query_migrate(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_MIGRATE_SET_CAPABILITIES_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_MIGRATE_SET_CAPABILITIES) || \
    false)

static inline void _nocheck__trace_qmp_enter_migrate_set_capabilities(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_MIGRATE_SET_CAPABILITIES) && qemu_loglevel_mask(LOG_TRACE)) {
#line 5 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_enter_migrate_set_capabilities " "%s" "\n", json);
#line 235 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_enter_migrate_set_capabilities(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_migrate_set_capabilities(json);
    }
}

#define TRACE_QMP_EXIT_MIGRATE_SET_CAPABILITIES_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_MIGRATE_SET_CAPABILITIES) || \
    false)

static inline void _nocheck__trace_qmp_exit_migrate_set_capabilities(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_MIGRATE_SET_CAPABILITIES) && qemu_loglevel_mask(LOG_TRACE)) {
#line 6 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_exit_migrate_set_capabilities " "%s %d" "\n", result, succeeded);
#line 255 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_exit_migrate_set_capabilities(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_migrate_set_capabilities(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_QUERY_MIGRATE_CAPABILITIES_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_QUERY_MIGRATE_CAPABILITIES) || \
    false)

static inline void _nocheck__trace_qmp_enter_query_migrate_capabilities(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_QUERY_MIGRATE_CAPABILITIES) && qemu_loglevel_mask(LOG_TRACE)) {
#line 7 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_enter_query_migrate_capabilities " "%s" "\n", json);
#line 275 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_enter_query_migrate_capabilities(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_query_migrate_capabilities(json);
    }
}

#define TRACE_QMP_EXIT_QUERY_MIGRATE_CAPABILITIES_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_QUERY_MIGRATE_CAPABILITIES) || \
    false)

static inline void _nocheck__trace_qmp_exit_query_migrate_capabilities(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_QUERY_MIGRATE_CAPABILITIES) && qemu_loglevel_mask(LOG_TRACE)) {
#line 8 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_exit_query_migrate_capabilities " "%s %d" "\n", result, succeeded);
#line 295 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_exit_query_migrate_capabilities(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_query_migrate_capabilities(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_MIGRATE_SET_PARAMETERS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_MIGRATE_SET_PARAMETERS) || \
    false)

static inline void _nocheck__trace_qmp_enter_migrate_set_parameters(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_MIGRATE_SET_PARAMETERS) && qemu_loglevel_mask(LOG_TRACE)) {
#line 9 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_enter_migrate_set_parameters " "%s" "\n", json);
#line 315 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_enter_migrate_set_parameters(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_migrate_set_parameters(json);
    }
}

#define TRACE_QMP_EXIT_MIGRATE_SET_PARAMETERS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_MIGRATE_SET_PARAMETERS) || \
    false)

static inline void _nocheck__trace_qmp_exit_migrate_set_parameters(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_MIGRATE_SET_PARAMETERS) && qemu_loglevel_mask(LOG_TRACE)) {
#line 10 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_exit_migrate_set_parameters " "%s %d" "\n", result, succeeded);
#line 335 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_exit_migrate_set_parameters(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_migrate_set_parameters(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_QUERY_MIGRATE_PARAMETERS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_QUERY_MIGRATE_PARAMETERS) || \
    false)

static inline void _nocheck__trace_qmp_enter_query_migrate_parameters(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_QUERY_MIGRATE_PARAMETERS) && qemu_loglevel_mask(LOG_TRACE)) {
#line 11 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_enter_query_migrate_parameters " "%s" "\n", json);
#line 355 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_enter_query_migrate_parameters(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_query_migrate_parameters(json);
    }
}

#define TRACE_QMP_EXIT_QUERY_MIGRATE_PARAMETERS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_QUERY_MIGRATE_PARAMETERS) || \
    false)

static inline void _nocheck__trace_qmp_exit_query_migrate_parameters(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_QUERY_MIGRATE_PARAMETERS) && qemu_loglevel_mask(LOG_TRACE)) {
#line 12 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_exit_query_migrate_parameters " "%s %d" "\n", result, succeeded);
#line 375 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_exit_query_migrate_parameters(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_query_migrate_parameters(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_MIGRATE_START_POSTCOPY_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_MIGRATE_START_POSTCOPY) || \
    false)

static inline void _nocheck__trace_qmp_enter_migrate_start_postcopy(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_MIGRATE_START_POSTCOPY) && qemu_loglevel_mask(LOG_TRACE)) {
#line 13 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_enter_migrate_start_postcopy " "%s" "\n", json);
#line 395 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_enter_migrate_start_postcopy(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_migrate_start_postcopy(json);
    }
}

#define TRACE_QMP_EXIT_MIGRATE_START_POSTCOPY_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_MIGRATE_START_POSTCOPY) || \
    false)

static inline void _nocheck__trace_qmp_exit_migrate_start_postcopy(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_MIGRATE_START_POSTCOPY) && qemu_loglevel_mask(LOG_TRACE)) {
#line 14 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_exit_migrate_start_postcopy " "%s %d" "\n", result, succeeded);
#line 415 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_exit_migrate_start_postcopy(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_migrate_start_postcopy(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_X_COLO_LOST_HEARTBEAT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_X_COLO_LOST_HEARTBEAT) || \
    false)

static inline void _nocheck__trace_qmp_enter_x_colo_lost_heartbeat(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_X_COLO_LOST_HEARTBEAT) && qemu_loglevel_mask(LOG_TRACE)) {
#line 15 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_enter_x_colo_lost_heartbeat " "%s" "\n", json);
#line 435 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_enter_x_colo_lost_heartbeat(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_x_colo_lost_heartbeat(json);
    }
}

#define TRACE_QMP_EXIT_X_COLO_LOST_HEARTBEAT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_X_COLO_LOST_HEARTBEAT) || \
    false)

static inline void _nocheck__trace_qmp_exit_x_colo_lost_heartbeat(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_X_COLO_LOST_HEARTBEAT) && qemu_loglevel_mask(LOG_TRACE)) {
#line 16 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_exit_x_colo_lost_heartbeat " "%s %d" "\n", result, succeeded);
#line 455 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_exit_x_colo_lost_heartbeat(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_x_colo_lost_heartbeat(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_MIGRATE_CANCEL_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_MIGRATE_CANCEL) || \
    false)

static inline void _nocheck__trace_qmp_enter_migrate_cancel(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_MIGRATE_CANCEL) && qemu_loglevel_mask(LOG_TRACE)) {
#line 17 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_enter_migrate_cancel " "%s" "\n", json);
#line 475 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_enter_migrate_cancel(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_migrate_cancel(json);
    }
}

#define TRACE_QMP_EXIT_MIGRATE_CANCEL_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_MIGRATE_CANCEL) || \
    false)

static inline void _nocheck__trace_qmp_exit_migrate_cancel(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_MIGRATE_CANCEL) && qemu_loglevel_mask(LOG_TRACE)) {
#line 18 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_exit_migrate_cancel " "%s %d" "\n", result, succeeded);
#line 495 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_exit_migrate_cancel(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_migrate_cancel(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_MIGRATE_CONTINUE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_MIGRATE_CONTINUE) || \
    false)

static inline void _nocheck__trace_qmp_enter_migrate_continue(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_MIGRATE_CONTINUE) && qemu_loglevel_mask(LOG_TRACE)) {
#line 19 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_enter_migrate_continue " "%s" "\n", json);
#line 515 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_enter_migrate_continue(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_migrate_continue(json);
    }
}

#define TRACE_QMP_EXIT_MIGRATE_CONTINUE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_MIGRATE_CONTINUE) || \
    false)

static inline void _nocheck__trace_qmp_exit_migrate_continue(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_MIGRATE_CONTINUE) && qemu_loglevel_mask(LOG_TRACE)) {
#line 20 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_exit_migrate_continue " "%s %d" "\n", result, succeeded);
#line 535 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_exit_migrate_continue(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_migrate_continue(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_MIGRATE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_MIGRATE) || \
    false)

static inline void _nocheck__trace_qmp_enter_migrate(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_MIGRATE) && qemu_loglevel_mask(LOG_TRACE)) {
#line 21 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_enter_migrate " "%s" "\n", json);
#line 555 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_enter_migrate(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_migrate(json);
    }
}

#define TRACE_QMP_EXIT_MIGRATE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_MIGRATE) || \
    false)

static inline void _nocheck__trace_qmp_exit_migrate(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_MIGRATE) && qemu_loglevel_mask(LOG_TRACE)) {
#line 22 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_exit_migrate " "%s %d" "\n", result, succeeded);
#line 575 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_exit_migrate(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_migrate(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_MIGRATE_INCOMING_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_MIGRATE_INCOMING) || \
    false)

static inline void _nocheck__trace_qmp_enter_migrate_incoming(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_MIGRATE_INCOMING) && qemu_loglevel_mask(LOG_TRACE)) {
#line 23 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_enter_migrate_incoming " "%s" "\n", json);
#line 595 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_enter_migrate_incoming(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_migrate_incoming(json);
    }
}

#define TRACE_QMP_EXIT_MIGRATE_INCOMING_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_MIGRATE_INCOMING) || \
    false)

static inline void _nocheck__trace_qmp_exit_migrate_incoming(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_MIGRATE_INCOMING) && qemu_loglevel_mask(LOG_TRACE)) {
#line 24 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_exit_migrate_incoming " "%s %d" "\n", result, succeeded);
#line 615 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_exit_migrate_incoming(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_migrate_incoming(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_XEN_SAVE_DEVICES_STATE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_XEN_SAVE_DEVICES_STATE) || \
    false)

static inline void _nocheck__trace_qmp_enter_xen_save_devices_state(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_XEN_SAVE_DEVICES_STATE) && qemu_loglevel_mask(LOG_TRACE)) {
#line 25 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_enter_xen_save_devices_state " "%s" "\n", json);
#line 635 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_enter_xen_save_devices_state(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_xen_save_devices_state(json);
    }
}

#define TRACE_QMP_EXIT_XEN_SAVE_DEVICES_STATE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_XEN_SAVE_DEVICES_STATE) || \
    false)

static inline void _nocheck__trace_qmp_exit_xen_save_devices_state(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_XEN_SAVE_DEVICES_STATE) && qemu_loglevel_mask(LOG_TRACE)) {
#line 26 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_exit_xen_save_devices_state " "%s %d" "\n", result, succeeded);
#line 655 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_exit_xen_save_devices_state(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_xen_save_devices_state(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_XEN_SET_GLOBAL_DIRTY_LOG_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_XEN_SET_GLOBAL_DIRTY_LOG) || \
    false)

static inline void _nocheck__trace_qmp_enter_xen_set_global_dirty_log(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_XEN_SET_GLOBAL_DIRTY_LOG) && qemu_loglevel_mask(LOG_TRACE)) {
#line 27 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_enter_xen_set_global_dirty_log " "%s" "\n", json);
#line 675 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_enter_xen_set_global_dirty_log(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_xen_set_global_dirty_log(json);
    }
}

#define TRACE_QMP_EXIT_XEN_SET_GLOBAL_DIRTY_LOG_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_XEN_SET_GLOBAL_DIRTY_LOG) || \
    false)

static inline void _nocheck__trace_qmp_exit_xen_set_global_dirty_log(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_XEN_SET_GLOBAL_DIRTY_LOG) && qemu_loglevel_mask(LOG_TRACE)) {
#line 28 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_exit_xen_set_global_dirty_log " "%s %d" "\n", result, succeeded);
#line 695 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_exit_xen_set_global_dirty_log(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_xen_set_global_dirty_log(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_XEN_LOAD_DEVICES_STATE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_XEN_LOAD_DEVICES_STATE) || \
    false)

static inline void _nocheck__trace_qmp_enter_xen_load_devices_state(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_XEN_LOAD_DEVICES_STATE) && qemu_loglevel_mask(LOG_TRACE)) {
#line 29 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_enter_xen_load_devices_state " "%s" "\n", json);
#line 715 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_enter_xen_load_devices_state(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_xen_load_devices_state(json);
    }
}

#define TRACE_QMP_EXIT_XEN_LOAD_DEVICES_STATE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_XEN_LOAD_DEVICES_STATE) || \
    false)

static inline void _nocheck__trace_qmp_exit_xen_load_devices_state(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_XEN_LOAD_DEVICES_STATE) && qemu_loglevel_mask(LOG_TRACE)) {
#line 30 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_exit_xen_load_devices_state " "%s %d" "\n", result, succeeded);
#line 735 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_exit_xen_load_devices_state(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_xen_load_devices_state(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_XEN_SET_REPLICATION_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_XEN_SET_REPLICATION) || \
    false)

static inline void _nocheck__trace_qmp_enter_xen_set_replication(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_XEN_SET_REPLICATION) && qemu_loglevel_mask(LOG_TRACE)) {
#line 31 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_enter_xen_set_replication " "%s" "\n", json);
#line 755 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_enter_xen_set_replication(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_xen_set_replication(json);
    }
}

#define TRACE_QMP_EXIT_XEN_SET_REPLICATION_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_XEN_SET_REPLICATION) || \
    false)

static inline void _nocheck__trace_qmp_exit_xen_set_replication(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_XEN_SET_REPLICATION) && qemu_loglevel_mask(LOG_TRACE)) {
#line 32 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_exit_xen_set_replication " "%s %d" "\n", result, succeeded);
#line 775 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_exit_xen_set_replication(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_xen_set_replication(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_QUERY_XEN_REPLICATION_STATUS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_QUERY_XEN_REPLICATION_STATUS) || \
    false)

static inline void _nocheck__trace_qmp_enter_query_xen_replication_status(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_QUERY_XEN_REPLICATION_STATUS) && qemu_loglevel_mask(LOG_TRACE)) {
#line 33 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_enter_query_xen_replication_status " "%s" "\n", json);
#line 795 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_enter_query_xen_replication_status(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_query_xen_replication_status(json);
    }
}

#define TRACE_QMP_EXIT_QUERY_XEN_REPLICATION_STATUS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_QUERY_XEN_REPLICATION_STATUS) || \
    false)

static inline void _nocheck__trace_qmp_exit_query_xen_replication_status(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_QUERY_XEN_REPLICATION_STATUS) && qemu_loglevel_mask(LOG_TRACE)) {
#line 34 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_exit_query_xen_replication_status " "%s %d" "\n", result, succeeded);
#line 815 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_exit_query_xen_replication_status(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_query_xen_replication_status(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_XEN_COLO_DO_CHECKPOINT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_XEN_COLO_DO_CHECKPOINT) || \
    false)

static inline void _nocheck__trace_qmp_enter_xen_colo_do_checkpoint(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_XEN_COLO_DO_CHECKPOINT) && qemu_loglevel_mask(LOG_TRACE)) {
#line 35 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_enter_xen_colo_do_checkpoint " "%s" "\n", json);
#line 835 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_enter_xen_colo_do_checkpoint(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_xen_colo_do_checkpoint(json);
    }
}

#define TRACE_QMP_EXIT_XEN_COLO_DO_CHECKPOINT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_XEN_COLO_DO_CHECKPOINT) || \
    false)

static inline void _nocheck__trace_qmp_exit_xen_colo_do_checkpoint(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_XEN_COLO_DO_CHECKPOINT) && qemu_loglevel_mask(LOG_TRACE)) {
#line 36 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_exit_xen_colo_do_checkpoint " "%s %d" "\n", result, succeeded);
#line 855 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_exit_xen_colo_do_checkpoint(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_xen_colo_do_checkpoint(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_QUERY_COLO_STATUS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_QUERY_COLO_STATUS) || \
    false)

static inline void _nocheck__trace_qmp_enter_query_colo_status(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_QUERY_COLO_STATUS) && qemu_loglevel_mask(LOG_TRACE)) {
#line 37 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_enter_query_colo_status " "%s" "\n", json);
#line 875 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_enter_query_colo_status(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_query_colo_status(json);
    }
}

#define TRACE_QMP_EXIT_QUERY_COLO_STATUS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_QUERY_COLO_STATUS) || \
    false)

static inline void _nocheck__trace_qmp_exit_query_colo_status(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_QUERY_COLO_STATUS) && qemu_loglevel_mask(LOG_TRACE)) {
#line 38 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_exit_query_colo_status " "%s %d" "\n", result, succeeded);
#line 895 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_exit_query_colo_status(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_query_colo_status(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_MIGRATE_RECOVER_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_MIGRATE_RECOVER) || \
    false)

static inline void _nocheck__trace_qmp_enter_migrate_recover(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_MIGRATE_RECOVER) && qemu_loglevel_mask(LOG_TRACE)) {
#line 39 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_enter_migrate_recover " "%s" "\n", json);
#line 915 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_enter_migrate_recover(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_migrate_recover(json);
    }
}

#define TRACE_QMP_EXIT_MIGRATE_RECOVER_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_MIGRATE_RECOVER) || \
    false)

static inline void _nocheck__trace_qmp_exit_migrate_recover(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_MIGRATE_RECOVER) && qemu_loglevel_mask(LOG_TRACE)) {
#line 40 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_exit_migrate_recover " "%s %d" "\n", result, succeeded);
#line 935 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_exit_migrate_recover(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_migrate_recover(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_MIGRATE_PAUSE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_MIGRATE_PAUSE) || \
    false)

static inline void _nocheck__trace_qmp_enter_migrate_pause(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_MIGRATE_PAUSE) && qemu_loglevel_mask(LOG_TRACE)) {
#line 41 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_enter_migrate_pause " "%s" "\n", json);
#line 955 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_enter_migrate_pause(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_migrate_pause(json);
    }
}

#define TRACE_QMP_EXIT_MIGRATE_PAUSE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_MIGRATE_PAUSE) || \
    false)

static inline void _nocheck__trace_qmp_exit_migrate_pause(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_MIGRATE_PAUSE) && qemu_loglevel_mask(LOG_TRACE)) {
#line 42 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_exit_migrate_pause " "%s %d" "\n", result, succeeded);
#line 975 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_exit_migrate_pause(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_migrate_pause(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_CALC_DIRTY_RATE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_CALC_DIRTY_RATE) || \
    false)

static inline void _nocheck__trace_qmp_enter_calc_dirty_rate(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_CALC_DIRTY_RATE) && qemu_loglevel_mask(LOG_TRACE)) {
#line 43 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_enter_calc_dirty_rate " "%s" "\n", json);
#line 995 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_enter_calc_dirty_rate(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_calc_dirty_rate(json);
    }
}

#define TRACE_QMP_EXIT_CALC_DIRTY_RATE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_CALC_DIRTY_RATE) || \
    false)

static inline void _nocheck__trace_qmp_exit_calc_dirty_rate(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_CALC_DIRTY_RATE) && qemu_loglevel_mask(LOG_TRACE)) {
#line 44 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_exit_calc_dirty_rate " "%s %d" "\n", result, succeeded);
#line 1015 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_exit_calc_dirty_rate(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_calc_dirty_rate(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_QUERY_DIRTY_RATE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_QUERY_DIRTY_RATE) || \
    false)

static inline void _nocheck__trace_qmp_enter_query_dirty_rate(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_QUERY_DIRTY_RATE) && qemu_loglevel_mask(LOG_TRACE)) {
#line 45 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_enter_query_dirty_rate " "%s" "\n", json);
#line 1035 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_enter_query_dirty_rate(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_query_dirty_rate(json);
    }
}

#define TRACE_QMP_EXIT_QUERY_DIRTY_RATE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_QUERY_DIRTY_RATE) || \
    false)

static inline void _nocheck__trace_qmp_exit_query_dirty_rate(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_QUERY_DIRTY_RATE) && qemu_loglevel_mask(LOG_TRACE)) {
#line 46 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_exit_query_dirty_rate " "%s %d" "\n", result, succeeded);
#line 1055 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_exit_query_dirty_rate(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_query_dirty_rate(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_SET_VCPU_DIRTY_LIMIT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_SET_VCPU_DIRTY_LIMIT) || \
    false)

static inline void _nocheck__trace_qmp_enter_set_vcpu_dirty_limit(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_SET_VCPU_DIRTY_LIMIT) && qemu_loglevel_mask(LOG_TRACE)) {
#line 47 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_enter_set_vcpu_dirty_limit " "%s" "\n", json);
#line 1075 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_enter_set_vcpu_dirty_limit(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_set_vcpu_dirty_limit(json);
    }
}

#define TRACE_QMP_EXIT_SET_VCPU_DIRTY_LIMIT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_SET_VCPU_DIRTY_LIMIT) || \
    false)

static inline void _nocheck__trace_qmp_exit_set_vcpu_dirty_limit(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_SET_VCPU_DIRTY_LIMIT) && qemu_loglevel_mask(LOG_TRACE)) {
#line 48 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_exit_set_vcpu_dirty_limit " "%s %d" "\n", result, succeeded);
#line 1095 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_exit_set_vcpu_dirty_limit(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_set_vcpu_dirty_limit(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_CANCEL_VCPU_DIRTY_LIMIT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_CANCEL_VCPU_DIRTY_LIMIT) || \
    false)

static inline void _nocheck__trace_qmp_enter_cancel_vcpu_dirty_limit(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_CANCEL_VCPU_DIRTY_LIMIT) && qemu_loglevel_mask(LOG_TRACE)) {
#line 49 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_enter_cancel_vcpu_dirty_limit " "%s" "\n", json);
#line 1115 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_enter_cancel_vcpu_dirty_limit(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_cancel_vcpu_dirty_limit(json);
    }
}

#define TRACE_QMP_EXIT_CANCEL_VCPU_DIRTY_LIMIT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_CANCEL_VCPU_DIRTY_LIMIT) || \
    false)

static inline void _nocheck__trace_qmp_exit_cancel_vcpu_dirty_limit(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_CANCEL_VCPU_DIRTY_LIMIT) && qemu_loglevel_mask(LOG_TRACE)) {
#line 50 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_exit_cancel_vcpu_dirty_limit " "%s %d" "\n", result, succeeded);
#line 1135 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_exit_cancel_vcpu_dirty_limit(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_cancel_vcpu_dirty_limit(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_QUERY_VCPU_DIRTY_LIMIT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_QUERY_VCPU_DIRTY_LIMIT) || \
    false)

static inline void _nocheck__trace_qmp_enter_query_vcpu_dirty_limit(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_QUERY_VCPU_DIRTY_LIMIT) && qemu_loglevel_mask(LOG_TRACE)) {
#line 51 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_enter_query_vcpu_dirty_limit " "%s" "\n", json);
#line 1155 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_enter_query_vcpu_dirty_limit(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_query_vcpu_dirty_limit(json);
    }
}

#define TRACE_QMP_EXIT_QUERY_VCPU_DIRTY_LIMIT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_QUERY_VCPU_DIRTY_LIMIT) || \
    false)

static inline void _nocheck__trace_qmp_exit_query_vcpu_dirty_limit(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_QUERY_VCPU_DIRTY_LIMIT) && qemu_loglevel_mask(LOG_TRACE)) {
#line 52 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_exit_query_vcpu_dirty_limit " "%s %d" "\n", result, succeeded);
#line 1175 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_exit_query_vcpu_dirty_limit(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_query_vcpu_dirty_limit(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_QUERY_MIGRATIONTHREADS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_QUERY_MIGRATIONTHREADS) || \
    false)

static inline void _nocheck__trace_qmp_enter_query_migrationthreads(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_QUERY_MIGRATIONTHREADS) && qemu_loglevel_mask(LOG_TRACE)) {
#line 53 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_enter_query_migrationthreads " "%s" "\n", json);
#line 1195 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_enter_query_migrationthreads(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_query_migrationthreads(json);
    }
}

#define TRACE_QMP_EXIT_QUERY_MIGRATIONTHREADS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_QUERY_MIGRATIONTHREADS) || \
    false)

static inline void _nocheck__trace_qmp_exit_query_migrationthreads(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_QUERY_MIGRATIONTHREADS) && qemu_loglevel_mask(LOG_TRACE)) {
#line 54 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_exit_query_migrationthreads " "%s %d" "\n", result, succeeded);
#line 1215 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_exit_query_migrationthreads(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_query_migrationthreads(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_SNAPSHOT_SAVE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_SNAPSHOT_SAVE) || \
    false)

static inline void _nocheck__trace_qmp_enter_snapshot_save(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_SNAPSHOT_SAVE) && qemu_loglevel_mask(LOG_TRACE)) {
#line 55 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_enter_snapshot_save " "%s" "\n", json);
#line 1235 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_enter_snapshot_save(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_snapshot_save(json);
    }
}

#define TRACE_QMP_EXIT_SNAPSHOT_SAVE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_SNAPSHOT_SAVE) || \
    false)

static inline void _nocheck__trace_qmp_exit_snapshot_save(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_SNAPSHOT_SAVE) && qemu_loglevel_mask(LOG_TRACE)) {
#line 56 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_exit_snapshot_save " "%s %d" "\n", result, succeeded);
#line 1255 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_exit_snapshot_save(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_snapshot_save(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_SNAPSHOT_LOAD_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_SNAPSHOT_LOAD) || \
    false)

static inline void _nocheck__trace_qmp_enter_snapshot_load(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_SNAPSHOT_LOAD) && qemu_loglevel_mask(LOG_TRACE)) {
#line 57 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_enter_snapshot_load " "%s" "\n", json);
#line 1275 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_enter_snapshot_load(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_snapshot_load(json);
    }
}

#define TRACE_QMP_EXIT_SNAPSHOT_LOAD_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_SNAPSHOT_LOAD) || \
    false)

static inline void _nocheck__trace_qmp_exit_snapshot_load(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_SNAPSHOT_LOAD) && qemu_loglevel_mask(LOG_TRACE)) {
#line 58 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_exit_snapshot_load " "%s %d" "\n", result, succeeded);
#line 1295 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_exit_snapshot_load(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_snapshot_load(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_SNAPSHOT_DELETE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_SNAPSHOT_DELETE) || \
    false)

static inline void _nocheck__trace_qmp_enter_snapshot_delete(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_SNAPSHOT_DELETE) && qemu_loglevel_mask(LOG_TRACE)) {
#line 59 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_enter_snapshot_delete " "%s" "\n", json);
#line 1315 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_enter_snapshot_delete(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_snapshot_delete(json);
    }
}

#define TRACE_QMP_EXIT_SNAPSHOT_DELETE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_SNAPSHOT_DELETE) || \
    false)

static inline void _nocheck__trace_qmp_exit_snapshot_delete(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_SNAPSHOT_DELETE) && qemu_loglevel_mask(LOG_TRACE)) {
#line 60 "qapi/qapi-commands-migration.trace-events"
        qemu_log("qmp_exit_snapshot_delete " "%s %d" "\n", result, succeeded);
#line 1335 "trace/trace-qapi_commands_migration_trace_events.h"
    }
}

static inline void trace_qmp_exit_snapshot_delete(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_snapshot_delete(result, succeeded);
    }
}
#endif /* TRACE_QAPI_COMMANDS_MIGRATION_TRACE_EVENTS_GENERATED_TRACERS_H */
