/* This file is autogenerated by tracetool, do not edit. */

#ifndef TRACE_QAPI_COMMANDS_VIRTIO_TRACE_EVENTS_GENERATED_TRACERS_H
#define TRACE_QAPI_COMMANDS_VIRTIO_TRACE_EVENTS_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_QMP_ENTER_X_QUERY_VIRTIO_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_X_QUERY_VIRTIO_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_X_QUERY_VIRTIO_STATUS_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_X_QUERY_VIRTIO_STATUS_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_X_QUERY_VIRTIO_QUEUE_STATUS_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_X_QUERY_VIRTIO_QUEUE_STATUS_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_X_QUERY_VIRTIO_VHOST_QUEUE_STATUS_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_X_QUERY_VIRTIO_VHOST_QUEUE_STATUS_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_X_QUERY_VIRTIO_QUEUE_ELEMENT_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_X_QUERY_VIRTIO_QUEUE_ELEMENT_EVENT;
extern uint16_t _TRACE_QMP_ENTER_X_QUERY_VIRTIO_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_X_QUERY_VIRTIO_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_X_QUERY_VIRTIO_STATUS_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_X_QUERY_VIRTIO_STATUS_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_X_QUERY_VIRTIO_QUEUE_STATUS_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_X_QUERY_VIRTIO_QUEUE_STATUS_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_X_QUERY_VIRTIO_VHOST_QUEUE_STATUS_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_X_QUERY_VIRTIO_VHOST_QUEUE_STATUS_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_X_QUERY_VIRTIO_QUEUE_ELEMENT_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_X_QUERY_VIRTIO_QUEUE_ELEMENT_DSTATE;
#define TRACE_QMP_ENTER_X_QUERY_VIRTIO_ENABLED 1
#define TRACE_QMP_EXIT_X_QUERY_VIRTIO_ENABLED 1
#define TRACE_QMP_ENTER_X_QUERY_VIRTIO_STATUS_ENABLED 1
#define TRACE_QMP_EXIT_X_QUERY_VIRTIO_STATUS_ENABLED 1
#define TRACE_QMP_ENTER_X_QUERY_VIRTIO_QUEUE_STATUS_ENABLED 1
#define TRACE_QMP_EXIT_X_QUERY_VIRTIO_QUEUE_STATUS_ENABLED 1
#define TRACE_QMP_ENTER_X_QUERY_VIRTIO_VHOST_QUEUE_STATUS_ENABLED 1
#define TRACE_QMP_EXIT_X_QUERY_VIRTIO_VHOST_QUEUE_STATUS_ENABLED 1
#define TRACE_QMP_ENTER_X_QUERY_VIRTIO_QUEUE_ELEMENT_ENABLED 1
#define TRACE_QMP_EXIT_X_QUERY_VIRTIO_QUEUE_ELEMENT_ENABLED 1
#include "qemu/log-for-trace.h"


#define TRACE_QMP_ENTER_X_QUERY_VIRTIO_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_X_QUERY_VIRTIO) || \
    false)

static inline void _nocheck__trace_qmp_enter_x_query_virtio(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_X_QUERY_VIRTIO) && qemu_loglevel_mask(LOG_TRACE)) {
#line 3 "qapi/qapi-commands-virtio.trace-events"
        qemu_log("qmp_enter_x_query_virtio " "%s" "\n", json);
#line 51 "trace/trace-qapi_commands_virtio_trace_events.h"
    }
}

static inline void trace_qmp_enter_x_query_virtio(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_x_query_virtio(json);
    }
}

#define TRACE_QMP_EXIT_X_QUERY_VIRTIO_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_X_QUERY_VIRTIO) || \
    false)

static inline void _nocheck__trace_qmp_exit_x_query_virtio(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_X_QUERY_VIRTIO) && qemu_loglevel_mask(LOG_TRACE)) {
#line 4 "qapi/qapi-commands-virtio.trace-events"
        qemu_log("qmp_exit_x_query_virtio " "%s %d" "\n", result, succeeded);
#line 71 "trace/trace-qapi_commands_virtio_trace_events.h"
    }
}

static inline void trace_qmp_exit_x_query_virtio(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_x_query_virtio(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_X_QUERY_VIRTIO_STATUS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_X_QUERY_VIRTIO_STATUS) || \
    false)

static inline void _nocheck__trace_qmp_enter_x_query_virtio_status(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_X_QUERY_VIRTIO_STATUS) && qemu_loglevel_mask(LOG_TRACE)) {
#line 5 "qapi/qapi-commands-virtio.trace-events"
        qemu_log("qmp_enter_x_query_virtio_status " "%s" "\n", json);
#line 91 "trace/trace-qapi_commands_virtio_trace_events.h"
    }
}

static inline void trace_qmp_enter_x_query_virtio_status(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_x_query_virtio_status(json);
    }
}

#define TRACE_QMP_EXIT_X_QUERY_VIRTIO_STATUS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_X_QUERY_VIRTIO_STATUS) || \
    false)

static inline void _nocheck__trace_qmp_exit_x_query_virtio_status(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_X_QUERY_VIRTIO_STATUS) && qemu_loglevel_mask(LOG_TRACE)) {
#line 6 "qapi/qapi-commands-virtio.trace-events"
        qemu_log("qmp_exit_x_query_virtio_status " "%s %d" "\n", result, succeeded);
#line 111 "trace/trace-qapi_commands_virtio_trace_events.h"
    }
}

static inline void trace_qmp_exit_x_query_virtio_status(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_x_query_virtio_status(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_X_QUERY_VIRTIO_QUEUE_STATUS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_X_QUERY_VIRTIO_QUEUE_STATUS) || \
    false)

static inline void _nocheck__trace_qmp_enter_x_query_virtio_queue_status(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_X_QUERY_VIRTIO_QUEUE_STATUS) && qemu_loglevel_mask(LOG_TRACE)) {
#line 7 "qapi/qapi-commands-virtio.trace-events"
        qemu_log("qmp_enter_x_query_virtio_queue_status " "%s" "\n", json);
#line 131 "trace/trace-qapi_commands_virtio_trace_events.h"
    }
}

static inline void trace_qmp_enter_x_query_virtio_queue_status(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_x_query_virtio_queue_status(json);
    }
}

#define TRACE_QMP_EXIT_X_QUERY_VIRTIO_QUEUE_STATUS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_X_QUERY_VIRTIO_QUEUE_STATUS) || \
    false)

static inline void _nocheck__trace_qmp_exit_x_query_virtio_queue_status(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_X_QUERY_VIRTIO_QUEUE_STATUS) && qemu_loglevel_mask(LOG_TRACE)) {
#line 8 "qapi/qapi-commands-virtio.trace-events"
        qemu_log("qmp_exit_x_query_virtio_queue_status " "%s %d" "\n", result, succeeded);
#line 151 "trace/trace-qapi_commands_virtio_trace_events.h"
    }
}

static inline void trace_qmp_exit_x_query_virtio_queue_status(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_x_query_virtio_queue_status(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_X_QUERY_VIRTIO_VHOST_QUEUE_STATUS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_X_QUERY_VIRTIO_VHOST_QUEUE_STATUS) || \
    false)

static inline void _nocheck__trace_qmp_enter_x_query_virtio_vhost_queue_status(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_X_QUERY_VIRTIO_VHOST_QUEUE_STATUS) && qemu_loglevel_mask(LOG_TRACE)) {
#line 9 "qapi/qapi-commands-virtio.trace-events"
        qemu_log("qmp_enter_x_query_virtio_vhost_queue_status " "%s" "\n", json);
#line 171 "trace/trace-qapi_commands_virtio_trace_events.h"
    }
}

static inline void trace_qmp_enter_x_query_virtio_vhost_queue_status(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_x_query_virtio_vhost_queue_status(json);
    }
}

#define TRACE_QMP_EXIT_X_QUERY_VIRTIO_VHOST_QUEUE_STATUS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_X_QUERY_VIRTIO_VHOST_QUEUE_STATUS) || \
    false)

static inline void _nocheck__trace_qmp_exit_x_query_virtio_vhost_queue_status(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_X_QUERY_VIRTIO_VHOST_QUEUE_STATUS) && qemu_loglevel_mask(LOG_TRACE)) {
#line 10 "qapi/qapi-commands-virtio.trace-events"
        qemu_log("qmp_exit_x_query_virtio_vhost_queue_status " "%s %d" "\n", result, succeeded);
#line 191 "trace/trace-qapi_commands_virtio_trace_events.h"
    }
}

static inline void trace_qmp_exit_x_query_virtio_vhost_queue_status(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_x_query_virtio_vhost_queue_status(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_X_QUERY_VIRTIO_QUEUE_ELEMENT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_X_QUERY_VIRTIO_QUEUE_ELEMENT) || \
    false)

static inline void _nocheck__trace_qmp_enter_x_query_virtio_queue_element(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_X_QUERY_VIRTIO_QUEUE_ELEMENT) && qemu_loglevel_mask(LOG_TRACE)) {
#line 11 "qapi/qapi-commands-virtio.trace-events"
        qemu_log("qmp_enter_x_query_virtio_queue_element " "%s" "\n", json);
#line 211 "trace/trace-qapi_commands_virtio_trace_events.h"
    }
}

static inline void trace_qmp_enter_x_query_virtio_queue_element(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_x_query_virtio_queue_element(json);
    }
}

#define TRACE_QMP_EXIT_X_QUERY_VIRTIO_QUEUE_ELEMENT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_X_QUERY_VIRTIO_QUEUE_ELEMENT) || \
    false)

static inline void _nocheck__trace_qmp_exit_x_query_virtio_queue_element(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_X_QUERY_VIRTIO_QUEUE_ELEMENT) && qemu_loglevel_mask(LOG_TRACE)) {
#line 12 "qapi/qapi-commands-virtio.trace-events"
        qemu_log("qmp_exit_x_query_virtio_queue_element " "%s %d" "\n", result, succeeded);
#line 231 "trace/trace-qapi_commands_virtio_trace_events.h"
    }
}

static inline void trace_qmp_exit_x_query_virtio_queue_element(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_x_query_virtio_queue_element(result, succeeded);
    }
}
#endif /* TRACE_QAPI_COMMANDS_VIRTIO_TRACE_EVENTS_GENERATED_TRACERS_H */
