/* This file is autogenerated by tracetool, do not edit. */

#ifndef TRACE_QAPI_COMMANDS_YANK_TRACE_EVENTS_GENERATED_TRACERS_H
#define TRACE_QAPI_COMMANDS_YANK_TRACE_EVENTS_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_QMP_ENTER_YANK_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_YANK_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_QUERY_YANK_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_QUERY_YANK_EVENT;
extern uint16_t _TRACE_QMP_ENTER_YANK_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_YANK_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_QUERY_YANK_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_QUERY_YANK_DSTATE;
#define TRACE_QMP_ENTER_YANK_ENABLED 1
#define TRACE_QMP_EXIT_YANK_ENABLED 1
#define TRACE_QMP_ENTER_QUERY_YANK_ENABLED 1
#define TRACE_QMP_EXIT_QUERY_YANK_ENABLED 1
#include "qemu/log-for-trace.h"


#define TRACE_QMP_ENTER_YANK_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_YANK) || \
    false)

static inline void _nocheck__trace_qmp_enter_yank(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_YANK) && qemu_loglevel_mask(LOG_TRACE)) {
#line 3 "qapi/qapi-commands-yank.trace-events"
        qemu_log("qmp_enter_yank " "%s" "\n", json);
#line 33 "trace/trace-qapi_commands_yank_trace_events.h"
    }
}

static inline void trace_qmp_enter_yank(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_yank(json);
    }
}

#define TRACE_QMP_EXIT_YANK_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_YANK) || \
    false)

static inline void _nocheck__trace_qmp_exit_yank(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_YANK) && qemu_loglevel_mask(LOG_TRACE)) {
#line 4 "qapi/qapi-commands-yank.trace-events"
        qemu_log("qmp_exit_yank " "%s %d" "\n", result, succeeded);
#line 53 "trace/trace-qapi_commands_yank_trace_events.h"
    }
}

static inline void trace_qmp_exit_yank(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_yank(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_QUERY_YANK_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_QUERY_YANK) || \
    false)

static inline void _nocheck__trace_qmp_enter_query_yank(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_QUERY_YANK) && qemu_loglevel_mask(LOG_TRACE)) {
#line 5 "qapi/qapi-commands-yank.trace-events"
        qemu_log("qmp_enter_query_yank " "%s" "\n", json);
#line 73 "trace/trace-qapi_commands_yank_trace_events.h"
    }
}

static inline void trace_qmp_enter_query_yank(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_query_yank(json);
    }
}

#define TRACE_QMP_EXIT_QUERY_YANK_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_QUERY_YANK) || \
    false)

static inline void _nocheck__trace_qmp_exit_query_yank(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_QUERY_YANK) && qemu_loglevel_mask(LOG_TRACE)) {
#line 6 "qapi/qapi-commands-yank.trace-events"
        qemu_log("qmp_exit_query_yank " "%s %d" "\n", result, succeeded);
#line 93 "trace/trace-qapi_commands_yank_trace_events.h"
    }
}

static inline void trace_qmp_exit_query_yank(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_query_yank(result, succeeded);
    }
}
#endif /* TRACE_QAPI_COMMANDS_YANK_TRACE_EVENTS_GENERATED_TRACERS_H */
