/* This file is autogenerated by tracetool, do not edit. */

#ifndef TRACE_BACKENDS_GENERATED_TRACERS_H
#define TRACE_BACKENDS_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_DBUS_VMSTATE_PRE_SAVE_EVENT;
extern TraceEvent _TRACE_DBUS_VMSTATE_POST_LOAD_EVENT;
extern TraceEvent _TRACE_DBUS_VMSTATE_LOADING_EVENT;
extern TraceEvent _TRACE_DBUS_VMSTATE_SAVING_EVENT;
extern TraceEvent _TRACE_IOMMUFD_CHANGE_PROCESS_EVENT;
extern TraceEvent _TRACE_IOMMUFD_BACKEND_CONNECT_EVENT;
extern TraceEvent _TRACE_IOMMUFD_BACKEND_DISCONNECT_EVENT;
extern TraceEvent _TRACE_IOMMU_BACKEND_SET_FD_EVENT;
extern TraceEvent _TRACE_IOMMUFD_BACKEND_MAP_DMA_EVENT;
extern TraceEvent _TRACE_IOMMUFD_BACKEND_MAP_FILE_DMA_EVENT;
extern TraceEvent _TRACE_IOMMUFD_BACKEND_UNMAP_DMA_NON_EXIST_EVENT;
extern TraceEvent _TRACE_IOMMUFD_BACKEND_UNMAP_DMA_EVENT;
extern TraceEvent _TRACE_IOMMUFD_BACKEND_ALLOC_IOAS_EVENT;
extern TraceEvent _TRACE_IOMMUFD_BACKEND_ALLOC_HWPT_EVENT;
extern TraceEvent _TRACE_IOMMUFD_BACKEND_FREE_ID_EVENT;
extern TraceEvent _TRACE_IOMMUFD_BACKEND_SET_DIRTY_EVENT;
extern TraceEvent _TRACE_IOMMUFD_BACKEND_GET_DIRTY_BITMAP_EVENT;
extern TraceEvent _TRACE_IOMMUFD_BACKEND_INVALIDATE_CACHE_EVENT;
extern uint16_t _TRACE_DBUS_VMSTATE_PRE_SAVE_DSTATE;
extern uint16_t _TRACE_DBUS_VMSTATE_POST_LOAD_DSTATE;
extern uint16_t _TRACE_DBUS_VMSTATE_LOADING_DSTATE;
extern uint16_t _TRACE_DBUS_VMSTATE_SAVING_DSTATE;
extern uint16_t _TRACE_IOMMUFD_CHANGE_PROCESS_DSTATE;
extern uint16_t _TRACE_IOMMUFD_BACKEND_CONNECT_DSTATE;
extern uint16_t _TRACE_IOMMUFD_BACKEND_DISCONNECT_DSTATE;
extern uint16_t _TRACE_IOMMU_BACKEND_SET_FD_DSTATE;
extern uint16_t _TRACE_IOMMUFD_BACKEND_MAP_DMA_DSTATE;
extern uint16_t _TRACE_IOMMUFD_BACKEND_MAP_FILE_DMA_DSTATE;
extern uint16_t _TRACE_IOMMUFD_BACKEND_UNMAP_DMA_NON_EXIST_DSTATE;
extern uint16_t _TRACE_IOMMUFD_BACKEND_UNMAP_DMA_DSTATE;
extern uint16_t _TRACE_IOMMUFD_BACKEND_ALLOC_IOAS_DSTATE;
extern uint16_t _TRACE_IOMMUFD_BACKEND_ALLOC_HWPT_DSTATE;
extern uint16_t _TRACE_IOMMUFD_BACKEND_FREE_ID_DSTATE;
extern uint16_t _TRACE_IOMMUFD_BACKEND_SET_DIRTY_DSTATE;
extern uint16_t _TRACE_IOMMUFD_BACKEND_GET_DIRTY_BITMAP_DSTATE;
extern uint16_t _TRACE_IOMMUFD_BACKEND_INVALIDATE_CACHE_DSTATE;
#define TRACE_DBUS_VMSTATE_PRE_SAVE_ENABLED 1
#define TRACE_DBUS_VMSTATE_POST_LOAD_ENABLED 1
#define TRACE_DBUS_VMSTATE_LOADING_ENABLED 1
#define TRACE_DBUS_VMSTATE_SAVING_ENABLED 1
#define TRACE_IOMMUFD_CHANGE_PROCESS_ENABLED 1
#define TRACE_IOMMUFD_BACKEND_CONNECT_ENABLED 1
#define TRACE_IOMMUFD_BACKEND_DISCONNECT_ENABLED 1
#define TRACE_IOMMU_BACKEND_SET_FD_ENABLED 1
#define TRACE_IOMMUFD_BACKEND_MAP_DMA_ENABLED 1
#define TRACE_IOMMUFD_BACKEND_MAP_FILE_DMA_ENABLED 1
#define TRACE_IOMMUFD_BACKEND_UNMAP_DMA_NON_EXIST_ENABLED 1
#define TRACE_IOMMUFD_BACKEND_UNMAP_DMA_ENABLED 1
#define TRACE_IOMMUFD_BACKEND_ALLOC_IOAS_ENABLED 1
#define TRACE_IOMMUFD_BACKEND_ALLOC_HWPT_ENABLED 1
#define TRACE_IOMMUFD_BACKEND_FREE_ID_ENABLED 1
#define TRACE_IOMMUFD_BACKEND_SET_DIRTY_ENABLED 1
#define TRACE_IOMMUFD_BACKEND_GET_DIRTY_BITMAP_ENABLED 1
#define TRACE_IOMMUFD_BACKEND_INVALIDATE_CACHE_ENABLED 1
#include "qemu/log-for-trace.h"


#define TRACE_DBUS_VMSTATE_PRE_SAVE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_DBUS_VMSTATE_PRE_SAVE) || \
    false)

static inline void _nocheck__trace_dbus_vmstate_pre_save(void)
{
    if (trace_event_get_state(TRACE_DBUS_VMSTATE_PRE_SAVE) && qemu_loglevel_mask(LOG_TRACE)) {
#line 4 "../backends/trace-events"
        qemu_log("dbus_vmstate_pre_save "  "\n");
#line 75 "trace/trace-backends.h"
    }
}

static inline void trace_dbus_vmstate_pre_save(void)
{
    if (true) {
        _nocheck__trace_dbus_vmstate_pre_save();
    }
}

#define TRACE_DBUS_VMSTATE_POST_LOAD_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_DBUS_VMSTATE_POST_LOAD) || \
    false)

static inline void _nocheck__trace_dbus_vmstate_post_load(int version_id)
{
    if (trace_event_get_state(TRACE_DBUS_VMSTATE_POST_LOAD) && qemu_loglevel_mask(LOG_TRACE)) {
#line 5 "../backends/trace-events"
        qemu_log("dbus_vmstate_post_load " "version_id: %d" "\n", version_id);
#line 95 "trace/trace-backends.h"
    }
}

static inline void trace_dbus_vmstate_post_load(int version_id)
{
    if (true) {
        _nocheck__trace_dbus_vmstate_post_load(version_id);
    }
}

#define TRACE_DBUS_VMSTATE_LOADING_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_DBUS_VMSTATE_LOADING) || \
    false)

static inline void _nocheck__trace_dbus_vmstate_loading(const char * id)
{
    if (trace_event_get_state(TRACE_DBUS_VMSTATE_LOADING) && qemu_loglevel_mask(LOG_TRACE)) {
#line 6 "../backends/trace-events"
        qemu_log("dbus_vmstate_loading " "id: %s" "\n", id);
#line 115 "trace/trace-backends.h"
    }
}

static inline void trace_dbus_vmstate_loading(const char * id)
{
    if (true) {
        _nocheck__trace_dbus_vmstate_loading(id);
    }
}

#define TRACE_DBUS_VMSTATE_SAVING_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_DBUS_VMSTATE_SAVING) || \
    false)

static inline void _nocheck__trace_dbus_vmstate_saving(const char * id)
{
    if (trace_event_get_state(TRACE_DBUS_VMSTATE_SAVING) && qemu_loglevel_mask(LOG_TRACE)) {
#line 7 "../backends/trace-events"
        qemu_log("dbus_vmstate_saving " "id: %s" "\n", id);
#line 135 "trace/trace-backends.h"
    }
}

static inline void trace_dbus_vmstate_saving(const char * id)
{
    if (true) {
        _nocheck__trace_dbus_vmstate_saving(id);
    }
}

#define TRACE_IOMMUFD_CHANGE_PROCESS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_IOMMUFD_CHANGE_PROCESS) || \
    false)

static inline void _nocheck__trace_iommufd_change_process(int fd, bool ret)
{
    if (trace_event_get_state(TRACE_IOMMUFD_CHANGE_PROCESS) && qemu_loglevel_mask(LOG_TRACE)) {
#line 10 "../backends/trace-events"
        qemu_log("iommufd_change_process " "fd=%d (%d)" "\n", fd, ret);
#line 155 "trace/trace-backends.h"
    }
}

static inline void trace_iommufd_change_process(int fd, bool ret)
{
    if (true) {
        _nocheck__trace_iommufd_change_process(fd, ret);
    }
}

#define TRACE_IOMMUFD_BACKEND_CONNECT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_IOMMUFD_BACKEND_CONNECT) || \
    false)

static inline void _nocheck__trace_iommufd_backend_connect(int fd, bool owned, uint32_t users)
{
    if (trace_event_get_state(TRACE_IOMMUFD_BACKEND_CONNECT) && qemu_loglevel_mask(LOG_TRACE)) {
#line 11 "../backends/trace-events"
        qemu_log("iommufd_backend_connect " "fd=%d owned=%d users=%d" "\n", fd, owned, users);
#line 175 "trace/trace-backends.h"
    }
}

static inline void trace_iommufd_backend_connect(int fd, bool owned, uint32_t users)
{
    if (true) {
        _nocheck__trace_iommufd_backend_connect(fd, owned, users);
    }
}

#define TRACE_IOMMUFD_BACKEND_DISCONNECT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_IOMMUFD_BACKEND_DISCONNECT) || \
    false)

static inline void _nocheck__trace_iommufd_backend_disconnect(int fd, uint32_t users)
{
    if (trace_event_get_state(TRACE_IOMMUFD_BACKEND_DISCONNECT) && qemu_loglevel_mask(LOG_TRACE)) {
#line 12 "../backends/trace-events"
        qemu_log("iommufd_backend_disconnect " "fd=%d users=%d" "\n", fd, users);
#line 195 "trace/trace-backends.h"
    }
}

static inline void trace_iommufd_backend_disconnect(int fd, uint32_t users)
{
    if (true) {
        _nocheck__trace_iommufd_backend_disconnect(fd, users);
    }
}

#define TRACE_IOMMU_BACKEND_SET_FD_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_IOMMU_BACKEND_SET_FD) || \
    false)

static inline void _nocheck__trace_iommu_backend_set_fd(int fd)
{
    if (trace_event_get_state(TRACE_IOMMU_BACKEND_SET_FD) && qemu_loglevel_mask(LOG_TRACE)) {
#line 13 "../backends/trace-events"
        qemu_log("iommu_backend_set_fd " "pre-opened /dev/iommu fd=%d" "\n", fd);
#line 215 "trace/trace-backends.h"
    }
}

static inline void trace_iommu_backend_set_fd(int fd)
{
    if (true) {
        _nocheck__trace_iommu_backend_set_fd(fd);
    }
}

#define TRACE_IOMMUFD_BACKEND_MAP_DMA_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_IOMMUFD_BACKEND_MAP_DMA) || \
    false)

static inline void _nocheck__trace_iommufd_backend_map_dma(int iommufd, uint32_t ioas, uint64_t iova, uint64_t size, void * vaddr, bool readonly, int ret)
{
    if (trace_event_get_state(TRACE_IOMMUFD_BACKEND_MAP_DMA) && qemu_loglevel_mask(LOG_TRACE)) {
#line 14 "../backends/trace-events"
        qemu_log("iommufd_backend_map_dma " " iommufd=%d ioas=%d iova=0x%"PRIx64" size=0x%"PRIx64" addr=%p readonly=%d (%d)" "\n", iommufd, ioas, iova, size, vaddr, readonly, ret);
#line 235 "trace/trace-backends.h"
    }
}

static inline void trace_iommufd_backend_map_dma(int iommufd, uint32_t ioas, uint64_t iova, uint64_t size, void * vaddr, bool readonly, int ret)
{
    if (true) {
        _nocheck__trace_iommufd_backend_map_dma(iommufd, ioas, iova, size, vaddr, readonly, ret);
    }
}

#define TRACE_IOMMUFD_BACKEND_MAP_FILE_DMA_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_IOMMUFD_BACKEND_MAP_FILE_DMA) || \
    false)

static inline void _nocheck__trace_iommufd_backend_map_file_dma(int iommufd, uint32_t ioas, uint64_t iova, uint64_t size, int fd, unsigned long start, bool readonly, int ret)
{
    if (trace_event_get_state(TRACE_IOMMUFD_BACKEND_MAP_FILE_DMA) && qemu_loglevel_mask(LOG_TRACE)) {
#line 15 "../backends/trace-events"
        qemu_log("iommufd_backend_map_file_dma " " iommufd=%d ioas=%d iova=0x%"PRIx64" size=0x%"PRIx64" fd=%d start=%ld readonly=%d (%d)" "\n", iommufd, ioas, iova, size, fd, start, readonly, ret);
#line 255 "trace/trace-backends.h"
    }
}

static inline void trace_iommufd_backend_map_file_dma(int iommufd, uint32_t ioas, uint64_t iova, uint64_t size, int fd, unsigned long start, bool readonly, int ret)
{
    if (true) {
        _nocheck__trace_iommufd_backend_map_file_dma(iommufd, ioas, iova, size, fd, start, readonly, ret);
    }
}

#define TRACE_IOMMUFD_BACKEND_UNMAP_DMA_NON_EXIST_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_IOMMUFD_BACKEND_UNMAP_DMA_NON_EXIST) || \
    false)

static inline void _nocheck__trace_iommufd_backend_unmap_dma_non_exist(int iommufd, uint32_t ioas, uint64_t iova, uint64_t size, int ret)
{
    if (trace_event_get_state(TRACE_IOMMUFD_BACKEND_UNMAP_DMA_NON_EXIST) && qemu_loglevel_mask(LOG_TRACE)) {
#line 16 "../backends/trace-events"
        qemu_log("iommufd_backend_unmap_dma_non_exist " " Unmap nonexistent mapping: iommufd=%d ioas=%d iova=0x%"PRIx64" size=0x%"PRIx64" (%d)" "\n", iommufd, ioas, iova, size, ret);
#line 275 "trace/trace-backends.h"
    }
}

static inline void trace_iommufd_backend_unmap_dma_non_exist(int iommufd, uint32_t ioas, uint64_t iova, uint64_t size, int ret)
{
    if (true) {
        _nocheck__trace_iommufd_backend_unmap_dma_non_exist(iommufd, ioas, iova, size, ret);
    }
}

#define TRACE_IOMMUFD_BACKEND_UNMAP_DMA_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_IOMMUFD_BACKEND_UNMAP_DMA) || \
    false)

static inline void _nocheck__trace_iommufd_backend_unmap_dma(int iommufd, uint32_t ioas, uint64_t iova, uint64_t size, int ret)
{
    if (trace_event_get_state(TRACE_IOMMUFD_BACKEND_UNMAP_DMA) && qemu_loglevel_mask(LOG_TRACE)) {
#line 17 "../backends/trace-events"
        qemu_log("iommufd_backend_unmap_dma " " iommufd=%d ioas=%d iova=0x%"PRIx64" size=0x%"PRIx64" (%d)" "\n", iommufd, ioas, iova, size, ret);
#line 295 "trace/trace-backends.h"
    }
}

static inline void trace_iommufd_backend_unmap_dma(int iommufd, uint32_t ioas, uint64_t iova, uint64_t size, int ret)
{
    if (true) {
        _nocheck__trace_iommufd_backend_unmap_dma(iommufd, ioas, iova, size, ret);
    }
}

#define TRACE_IOMMUFD_BACKEND_ALLOC_IOAS_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_IOMMUFD_BACKEND_ALLOC_IOAS) || \
    false)

static inline void _nocheck__trace_iommufd_backend_alloc_ioas(int iommufd, uint32_t ioas)
{
    if (trace_event_get_state(TRACE_IOMMUFD_BACKEND_ALLOC_IOAS) && qemu_loglevel_mask(LOG_TRACE)) {
#line 18 "../backends/trace-events"
        qemu_log("iommufd_backend_alloc_ioas " " iommufd=%d ioas=%d" "\n", iommufd, ioas);
#line 315 "trace/trace-backends.h"
    }
}

static inline void trace_iommufd_backend_alloc_ioas(int iommufd, uint32_t ioas)
{
    if (true) {
        _nocheck__trace_iommufd_backend_alloc_ioas(iommufd, ioas);
    }
}

#define TRACE_IOMMUFD_BACKEND_ALLOC_HWPT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_IOMMUFD_BACKEND_ALLOC_HWPT) || \
    false)

static inline void _nocheck__trace_iommufd_backend_alloc_hwpt(int iommufd, uint32_t dev_id, uint32_t pt_id, uint32_t flags, uint32_t hwpt_type, uint32_t len, uint64_t data_ptr, uint32_t out_hwpt_id, int ret)
{
    if (trace_event_get_state(TRACE_IOMMUFD_BACKEND_ALLOC_HWPT) && qemu_loglevel_mask(LOG_TRACE)) {
#line 19 "../backends/trace-events"
        qemu_log("iommufd_backend_alloc_hwpt " " iommufd=%d dev_id=%u pt_id=%u flags=0x%x hwpt_type=%u len=%u data_ptr=0x%"PRIx64" out_hwpt=%u (%d)" "\n", iommufd, dev_id, pt_id, flags, hwpt_type, len, data_ptr, out_hwpt_id, ret);
#line 335 "trace/trace-backends.h"
    }
}

static inline void trace_iommufd_backend_alloc_hwpt(int iommufd, uint32_t dev_id, uint32_t pt_id, uint32_t flags, uint32_t hwpt_type, uint32_t len, uint64_t data_ptr, uint32_t out_hwpt_id, int ret)
{
    if (true) {
        _nocheck__trace_iommufd_backend_alloc_hwpt(iommufd, dev_id, pt_id, flags, hwpt_type, len, data_ptr, out_hwpt_id, ret);
    }
}

#define TRACE_IOMMUFD_BACKEND_FREE_ID_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_IOMMUFD_BACKEND_FREE_ID) || \
    false)

static inline void _nocheck__trace_iommufd_backend_free_id(int iommufd, uint32_t id, int ret)
{
    if (trace_event_get_state(TRACE_IOMMUFD_BACKEND_FREE_ID) && qemu_loglevel_mask(LOG_TRACE)) {
#line 20 "../backends/trace-events"
        qemu_log("iommufd_backend_free_id " " iommufd=%d id=%d (%d)" "\n", iommufd, id, ret);
#line 355 "trace/trace-backends.h"
    }
}

static inline void trace_iommufd_backend_free_id(int iommufd, uint32_t id, int ret)
{
    if (true) {
        _nocheck__trace_iommufd_backend_free_id(iommufd, id, ret);
    }
}

#define TRACE_IOMMUFD_BACKEND_SET_DIRTY_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_IOMMUFD_BACKEND_SET_DIRTY) || \
    false)

static inline void _nocheck__trace_iommufd_backend_set_dirty(int iommufd, uint32_t hwpt_id, bool start, int ret)
{
    if (trace_event_get_state(TRACE_IOMMUFD_BACKEND_SET_DIRTY) && qemu_loglevel_mask(LOG_TRACE)) {
#line 21 "../backends/trace-events"
        qemu_log("iommufd_backend_set_dirty " " iommufd=%d hwpt=%u enable=%d (%d)" "\n", iommufd, hwpt_id, start, ret);
#line 375 "trace/trace-backends.h"
    }
}

static inline void trace_iommufd_backend_set_dirty(int iommufd, uint32_t hwpt_id, bool start, int ret)
{
    if (true) {
        _nocheck__trace_iommufd_backend_set_dirty(iommufd, hwpt_id, start, ret);
    }
}

#define TRACE_IOMMUFD_BACKEND_GET_DIRTY_BITMAP_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_IOMMUFD_BACKEND_GET_DIRTY_BITMAP) || \
    false)

static inline void _nocheck__trace_iommufd_backend_get_dirty_bitmap(int iommufd, uint32_t hwpt_id, uint64_t iova, uint64_t size, uint64_t page_size, int ret)
{
    if (trace_event_get_state(TRACE_IOMMUFD_BACKEND_GET_DIRTY_BITMAP) && qemu_loglevel_mask(LOG_TRACE)) {
#line 22 "../backends/trace-events"
        qemu_log("iommufd_backend_get_dirty_bitmap " " iommufd=%d hwpt=%u iova=0x%"PRIx64" size=0x%"PRIx64" page_size=0x%"PRIx64" (%d)" "\n", iommufd, hwpt_id, iova, size, page_size, ret);
#line 395 "trace/trace-backends.h"
    }
}

static inline void trace_iommufd_backend_get_dirty_bitmap(int iommufd, uint32_t hwpt_id, uint64_t iova, uint64_t size, uint64_t page_size, int ret)
{
    if (true) {
        _nocheck__trace_iommufd_backend_get_dirty_bitmap(iommufd, hwpt_id, iova, size, page_size, ret);
    }
}

#define TRACE_IOMMUFD_BACKEND_INVALIDATE_CACHE_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_IOMMUFD_BACKEND_INVALIDATE_CACHE) || \
    false)

static inline void _nocheck__trace_iommufd_backend_invalidate_cache(int iommufd, uint32_t id, uint32_t data_type, uint32_t entry_len, uint32_t entry_num, uint32_t done_num, uint64_t data_ptr, int ret)
{
    if (trace_event_get_state(TRACE_IOMMUFD_BACKEND_INVALIDATE_CACHE) && qemu_loglevel_mask(LOG_TRACE)) {
#line 23 "../backends/trace-events"
        qemu_log("iommufd_backend_invalidate_cache " " iommufd=%d id=%u data_type=%u entry_len=%u entry_num=%u done_num=%u data_ptr=0x%"PRIx64" (%d)" "\n", iommufd, id, data_type, entry_len, entry_num, done_num, data_ptr, ret);
#line 415 "trace/trace-backends.h"
    }
}

static inline void trace_iommufd_backend_invalidate_cache(int iommufd, uint32_t id, uint32_t data_type, uint32_t entry_len, uint32_t entry_num, uint32_t done_num, uint64_t data_ptr, int ret)
{
    if (true) {
        _nocheck__trace_iommufd_backend_invalidate_cache(iommufd, id, data_type, entry_len, entry_num, done_num, data_ptr, ret);
    }
}
#endif /* TRACE_BACKENDS_GENERATED_TRACERS_H */
